version: "3"
services:
  postgres:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=tiny_task
      - POSTGRES_USER=tiny_task
      - POSTGRES_PASSWORD=demo123
    volumes:
      - tiny-task-postgres:/var/lib/postgresql/data
volumes:
  tiny-task-postgres: {}
